// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Entities.Models.ValueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("Description")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("Entities.Models.WorkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AddedChildrenCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AddedCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DecDayCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("FactStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("IncDayCost")
                        .HasColumnType("numeric");

                    b.Property<int>("MinimalDuration")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinimalDurationCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("NewPlannedStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("NormDuration")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlannedStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Entities.Models.WorkWorkEntity", b =>
                {
                    b.Property<Guid>("NextWorkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrevWorkId")
                        .HasColumnType("uuid");

                    b.HasKey("NextWorkId", "PrevWorkId");

                    b.HasIndex("PrevWorkId");

                    b.ToTable("WorkWorkEntity");
                });

            modelBuilder.Entity("Entities.Models.WorkWorkEntity", b =>
                {
                    b.HasOne("Entities.Models.WorkEntity", "NextWork")
                        .WithMany("PrevWorks")
                        .HasForeignKey("NextWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.WorkEntity", "PrevWork")
                        .WithMany("NextWorks")
                        .HasForeignKey("PrevWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
